language: java
jdk:
- openjdk8
sudo: false
install: "./installViaTravis.sh"
script: "./buildViaTravis.sh"
env:
  global:
  - secure: n03qjQU2tBwKeFNw29R0Xfj1wUVB4/Lccchoha01eFdFTUDUjcjlHRk2hzDb2W+7mVJWjvgLTtPMq2nhu9AjXA1IYnK0CdU1mi5EQc9B4nRUl95ChOe7AQcG53JX+JDwQMaF+nVP/cejTS1BTbduB1AMEoyZp1nKGEf1bqaiAA8=
  - secure: oib8WzNknT4A26RYKTPGuksyEnSPei0ww2uFFroMFJebInlVKxYxbH3Tua3XiSLcKE/oyiNIMOVVTIcb4WprdPYGOToFXNWFpE2c2koeo2acUldCrZUoX8dJ+qkoVC3y9h8c5ghNdTZxwy3jdZYIK6OqT2X5wMmEjBXZ01wDOo4=
  - secure: FeZcG11GkkdB8EgALMzx1dJRx5GhEj9Ap0MHULUsYiczZmLwIlkQ92gzV9xHCRpIISigWnxNS9DqGekpxZQtUqw+O9cRAfuBUsiB4Q03IrmRSFc52DL3UgKULtRBds5VNC5JmrEKKAMNACVdPj17ZGRatuR2kh6NV4/NeFvGKGw=
  - secure: m+IG6W8pjakNfXNyrTwqwOHkYkl3IL/OITgWDcz7OQXR91anrtObO2ujyRGb4abmUo76McTXY9nnQQ/fR9skrQCyt2dTP5gtQPm9kklI+Za2Pl/M3l+LYe3N2SY1JkDu86hiWGmYnSYqc8XgtsuBQAxESszBRIZPs29Yuoz8buE=
  - secure: gxBi/yZu/DLPb4neAt7saSLXb308Tg1Ss3k1BXWukxwh9zGBp1eGZ5EWJG1hvnBHDQbVQYJBkaH7/hZdSP0GJrEKW4O6+E90bf0pG0mVVfMVUIlZDRdgyatMN6eVj+/7cmB6K71wuji5ZNn3vvtSwMnLdfkLCoVqgbgwdGecj0s=
  - secure: Z1e3y/jp0t4iBwKACzJ/B3nizD5aVMUNhc/+zSx8J8jh+iM0PyjKbA1fqNbBi+UODiOSCqw/drZnHvXqvy5fecZ7EssD6ULQTKhhn21NsrrPJlVMPCnaZY/R1MeTNC9hG4Il9MzcNIlqSAf0ztnfGHEiFs9Idc2Q4bPJgH2RM5M=
cache:
  directories:
  - "$HOME/.gradle/caches"
