language: java
jdk:
- openjdk8
sudo: false
install: "./installViaTravis.sh"
script: "./buildViaTravis.sh"
cache:
  directories:
  - "$HOME/.gradle/caches"
env:
  global:
  - secure: Ae6S9GxUD7WaCwQn9XxnVUoqGFL6PikceeImL9XNH7b2tP9Y3sjQZiCSxHGYzYX4atg+Dy4ywVQaiGTlo4XdLZHHLBa33q4oKzuas0IhqACWWselwWcYlNhcWx/DNZUx3x+agkDBGvf9MC+medGsESRdIUCRnG4Ljvg4m3O+EDs=
  - secure: gPbwhkrptO9OW4yWovIaVTlQkUnrBfGw7d7LwCwJmJcOze9+o/nhH/HKsm9/WO9k3wqmHCvuDBlDFxr6seBagrPj6iXBCB4mEokC9pxv0HYE1HNhnBTKoNs6vfn+UuZxIYKuFMRnftdupBF36NS0A+wxL3MI17+A9xs62c3Ry1k=
  - secure: WHvLiiFINJi735SNqY5MFRkGz+BnQGoUEbTiVXtl9Imao+uNTS2SOVXHKSaYJRG6vKO9rKQRtjrkQUgnEqDXtZ+gPeEauh7d4hEmbQAuOM+m6aX1Ubw0wUs9RzrQ/V0pEENx/Rp3WHANy4N1fwfFS2g3TURIAcuOhHqOKzw2AtU=
  - secure: Nzx8h7j3J6Cfccy9GE50O7z2o+6lgr46FJjaRkWwzq5QNL73ghlKso7TiLYJPbp0eEGUbMBJPKTR54dghb4eWkgRWF5Y7W4uMJqBPi4Uz39PX0kcXba+z1wriHxyyvALG5R4aHSQJwa2x79vmi5+TZ6E85KJTh6trL8ZXD32hyQ=
  - secure: EKPPr2zDL66aOZOpZHLu/irdFtEjs9pjOLFEM5oGjL9pVduakLIvqcx2eG+5CH871HQOko75B6MKypwnFZ+oiKsByvuyCIFFr6DWCffU4Bht32+9RrgVvvT969Z3gSaQ41YzZIHTrXSTgkrVGB2d1i3VfJ66n1V6nVxp84aamHg=
  - secure: Sa8csXV0v8/FNR3snKafI3bYg2L7qJ2tqkNDW5SYOAVfxHs48J0rBCWO0B2vaJ+TCSkGlF5YHb/CAdI/83uitIsNh7GH2kyqaz/VlZXZ23eo6rUBUsdr+9zOLyXup/ls5I8XS7u0hekStgvgM0Lb6fy9lnTJgpP9/+jJrMSM0hM=
